#!/usr/bin/env bash
#
# Script name: dm-help
# Description: List all tldr pages with preview, and show man page of selected cmd.
# Dependencies: fzf, tldr, tree, jq, less, man
# GitLab: https://www.gitlab.com/dwt1/dmscripts
# License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
# Contributors: ZYT
#               Derek Taylor
#
### HELP FOR TLDR CONFIG
# downloaded tldr pages directory: ~/.local/share/tldr/

# Set with the flags "-e", "-u","-o pipefail" cause the script to fail
# if certain things happen, which is a good thing.  Otherwise, we can
# get hidden bugs that are hard to discover.
set -euo pipefail

# shellcheck disable=SC1091
source ./_dm-helper.sh 2>/dev/null || source _dm-helper.sh 2>/dev/null
# source /home/zyt/zyt-helper.sh 2>/dev/null
source_dmscripts_configs

# jq .commands[].name -r index.json
export TLDR_DB_DIR=~/.local/share/tldr
export TLDR_INDEX_JSON=${TLDR_DB_DIR}/index.json
export HELP_HUB_RUN_DIR=/run/user/1000/help_hub
[[ -d "$HELP_HUB_RUN_DIR" ]] || mkdir -p "$HELP_HUB_RUN_DIR" 

function list_tldr(){
	jq '.commands[]|"tldr#"+.platform[]+"#"+.name' -r $TLDR_INDEX_JSON
}
function list_man_pages(){
	man -k . | awk '{print "man#linux#"$0}'
}
function list_info(){
	info -k . | awk '{print "info#linux#"$0}'
}
function list_builtin_commands(){
	bash -c help -d | awk -F '  ' '/^ / {printf "builtin#bash#%s\nbuiltin#bash#%s\n", gensub(/ +.*/, "", "g", gensub(/^ */, "", 1,$1)), gensub(/ +.*/, "", "g", gensub(/^ */, "", 1,$NF))}'
}
#List property(designated by $2) of cmd designated by $1
function list_cmd_property(){
	jq --arg name "$1" --arg prop "$2" '.commands[]|select(.name==$name)|.[$prop].[]' -r $TLDR_INDEX_JSON
}
export -f list_cmd_property
#List supported languages of cmd designated by $1
function list_cmd_languages(){
	# jq --arg name "$1" '.commands[]|select(.name==$name)|.language.[]' -r $TLDR_INDEX_JSON
	list_cmd_property "$1" "language"
}
export -f list_cmd_languages
function list_help_topics(){
	if [[ -f "$HELP_HUB_RUN_DIR"/topics ]]; then
		cat "$HELP_HUB_RUN_DIR"/topics
	else
		echo -e "$(list_tldr)\n$(list_man_pages)\n$(list_info)\n$(list_builtin_commands)" | tee "$HELP_HUB_RUN_DIR"/topics
	fi
}

#Param1: tldr/man/help
#Param2: platform: linux/windows/..
#Param3: topic
function display_topic(){
	local expression
	case "$1" in
		builtin)
			local topic
			topic=$(echo "$3"|awk '{print $1}')
			help -m "$topic" | less
			;;
		tldr)
			if [ "$4" == preview ] ; then
				command tldr --platform "$2" "$3" | less
			else
				if info "$3" &>/dev/null;then
					pinfo "$3"
				elif man "$3" &>/dev/null;then
					expression="(progn (require 'man)(let ((Man-notify-method 'pushy))(man \"$3\")))"
					emacsclient.sh -e "$expression" || man "$3"
				else
					expression="(progn (require 'tldr)(tldr \"$3\"))"
					emacsclient.sh -e "$expression" || command tldr --platform "$2" "$3" | less
				fi
			fi
			;;
		man)
			# shellcheck disable=SC2046
			eval $(echo "$3" | awk -F '( \\()|)' '{print "local topic=\"" $1 "\"; local section=\"" $2 "\""}')
			if [ "$4" == preview ] ; then
				#shellcheck disable=SC2154
				man "$section" "$topic";
			else
				expression="(progn (require 'man)(let ((Man-notify-method 'pushy))(man \"$section $topic\")))"
				emacsclient.sh -e "$expression" || pinfo -a "$topic.$section";
			fi
			;;
		info)
			# shellcheck disable=SC2046
			eval $(echo "${*:3: ${#*}-3}" | awk -F ' --' 'match($1, /\((.*)\)(.*)/, groups) {print "local info_file=" groups[1] ";\n local node=\"" groups[2] ";"}')
			# shellcheck disable=SC2154
			if [ "${*: ${#*}}" == preview ] ; then
				info "($info_file)$node"
			else
				expression="(info \"\($info_file\)$node\")"
				emacsclient.sh -e "$expression" || pinfo "$info_file"
			fi
			;;
		*)
			help -m "${*:3}" | less ;;
	esac
	# command "$1" $(echo "$3" | awk '{print $1}')
}

export -f display_topic
main(){
	# list_commands && exit 0
	# list_cmd_languages $(echo -n "$(list_commands)" | fzf -e) 
	# list_cmd_property "[[" "platform"
	# exit 0
	while getopts "dfrh" arg 2>/dev/null; do
		:	
	done
	shift $((OPTIND - 1))
	set +u
	[[ -n $1 ]] && init_query=$1 || init_query=""
	set -u
	choice=$(echo -n "$(list_help_topics)"\
				 | fzf --query="$init_query" \
					   --delimiter '#'\
					   --exact\
					   --sort\
					   --with-nth '{1} {2} {3}'\
					   --accept-nth='{1,2,3}'\
					   --style full\
					   --bind 'focus:transform-preview-label(list_cmd_property {} "platform")'\
					   --bind "tab:execute(display_topic {1} {2} {3} view)"\
					   --preview='display_topic {1} {2} {3} preview') || exit 1
	set +e
	# shellcheck disable=SC2086
	# display_topic $(echo "$choice" | sed 's/#/ /g') view 
	# display_topic $(echo "${choice//#/ }") view
	display_topic ${choice//#/ } view
	wmctrl -a emacs
	# if whatis "$choice" > /dev/null 2>&1;then
	# 	man "$choice"
	# elif command help -m "$choice" > /dev/null 2>&1; then
	# 	command help -m "$choice"|less
	# else
	# 	:
	# fi
}
# shellcheck enable=quote-safe-variables

# # If script is run with NO argument, it will use 'dmenu'
# [ $no_opt = 1 ] && MENU=${DMENU} && [[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"

MENU="$(get_menu_program "$@")"
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"



# man -k . | fzf -e --preview 'man -f {1}' --accept-nth 1 | xargs man
